### ISSUE TITLE
HTTP Error 404 File not found, invalid path when selecting a folder if --servedir is set to "/"

### ISSUE THREAD

**Issue by jabefa** [ebraminio/pad.js#19]
If --servedir is set to "/" (or no --servedir is set and the working directory is "/"), the root path, when a folder is selected to show its contents through the UI it fails and the log prints "HTTP Error 404 File not found". It doesn't happen if --servedir is set to any other value

**Comment by ebraminio** [comment]
@jabefa Hi! I've just fixed this I think, feel free to check and raise any other issue you see, thanks 😊

**Comment by ebraminio** [comment]
Just amended the previous change, https://github.com/ebraminio/pad.js/commit/fc5afc90d53b9163a98a832964897fafeb9b3896
