### ISSUE TITLE
Allow creating nested files

### ISSUE THREAD

**Issue by Bekreth** [ebraminio/pad.js#21]
# About
Currently, if you want to POST a file to the server, the full filepath needs to exist prior to posting.  This creates some issues when trying to build file trees as each POST request needs to be preceded by multiple PUT requests to build the file tree before the final file can be created.

# Suggested Fix
Add a new startup config option `--allow-parent-creation` and setup POST to use the `fs.mkdir` function conditionally on the presence of this flag.

**Comment by ebraminio** [comment]
Done, thanks for the suggestion! It even motivated me to improve some other bits I liked to do sometime 😊

As "fs.realpathSync(path.replace(/[^\/\\]+$/, '')) + nativePathSep).indexOf(cwd) !== 0" is checking for valid directory (I know,  this line again, am sorry about it) I didn't add a new config but made this possible with `--follow-outside-links`. Once I can get rid of that line I'll enable this just always and not behind any flag.

Thanks 😊

**Comment by Bekreth** [comment]
@ebraminio  Wow, really fast turn around, thank you! Would you be able to push these updates to NPM? https://www.npmjs.com/package/pad.js

**Comment by ebraminio** [comment]
Oh, weird, I though CI setup did it already but now I see it didn't work for some reason, I made the publish anyway, thanks for letting me know 😊
